### ISSUE TITLE
The Google Drive link of the model checkpoints (~3.5GB) show models.tar.lz4 is in the owner's recycle bin

### ISSUE THREAD

**Issue by Wenqi-Ge** [columbia-ai-robotics/semantic-abstraction#5]
could you share a new link? Thank you very much!

**Comment by huy-ha** [comment]
Thank you for your interest in our work and for reporting the issue! I've updated the download instructions to remove the Google Drive option, and instead use wget.

**Comment by mamimaka** [comment]
> 
Hi @huy-ha, when I used wget to download model checkpoints, it said, "Fail: reject the connection." Is there any other way to download the model checkpoints?

**Comment by huy-ha** [comment]
It seems like Columbia's CS servers are down at the moment... Could you try wget again in a few hours? My apologies for the inconvenience!

**Comment by huy-ha** [comment]
It should work now!
